name: CI Build
run-name: CIBuild_${{ github.event_name }}_${{ github.ref_name }}_${{ github.run_number }}.${{ github.run_attempt }}

env:
  PRIMARY_BRANCH_NAME: main
  APP_MAJOR_VERSION: 1
  APP_MINOR_VERSION: 2
  PROJECT_NAME: NativeWindowsConsoleApplicationsRUST
  BUILD_CONFIG: release
  BRANCH_PREFIX_RELEASE_CANDIDATE: rc/
  CARGO_TERM_COLOR: always
  BASE_BUILD_OUTPUT_FOLDER: Output
  BASE_BUILD_COLLECT_FOLDER: Collect
  BASE_BUILD_ARTIFACTS_FOLDER: Artifacts

on:
  push:
    branches:
      - main
      - master
      - rc/**
      - feature/**
      - task/**
      - spike/**

  pull_request:
    branches:
      - master
      - main

  workflow_dispatch:

jobs:
  ##########################################################
  ## Pipeline Configuration and Setup
  setup:
    name: Setup Pipeline

    runs-on: ubuntu-latest

    steps:
    - name: Get Current Build Date
      run: |
        echo "build_date=$(date +'%y%j')" >> $GITHUB_ENV
        echo "build_year=$(date +'%Y')" >> $GITHUB_ENV

    - name: Evaluate pipeline conditions
      run: |
        is_primary_branch=false
        is_pull_request_build=false
        is_release_candidate_branch=false

        # Primary Branch ?
        if [ "${{ github.ref }}" == 'refs/heads/${{ env.PRIMARY_BRANCH_NAME }}' ]
        then
          is_primary_branch=true
        fi

        # Pull Request ?
        if [ "${{ github.event_name }}" == "pull_request" ]
        then
          is_pull_request_build=true
        fi

        # If Release Candidate branch ?
        if [[ "${{ github.ref }}" == refs/heads/${{ env.BRANCH_PREFIX_RELEASE_CANDIDATE }}* ]]
        then
          is_release_candidate_branch=true
        fi

        # Set for later steps
        echo "is_primary_branch=${is_primary_branch}" >> $GITHUB_ENV
        echo "is_pull_request_build=${is_pull_request_build}" >> $GITHUB_ENV
        echo "is_release_candidate_branch=${is_release_candidate_branch}" >> $GITHUB_ENV

    - name: Determine Tagging
      run: |
        should_tag=false

        if $is_primary_branch;
        then
            if ! $is_pull_request_build;
            then
                should_tag=true
            fi
        fi

        echo "should_tag=${should_tag}" >> $GITHUB_ENV

    - name: Determine GitHub Releasing
      run: |
        should_release=true
        release_is_draft=true
        release_is_prerelease=false
        release_modifier='-ci'

        if $is_primary_branch
        then
            release_is_draft=false
            release_is_prerelease=false
            release_modifier=''
        fi
        if $is_release_candidate_branch
        then
            release_modifier='-alpha'
        fi
        if $is_pull_request_build; then
            release_is_draft=false
            release_is_prerelease=true
            release_modifier='-beta'
        fi

        echo "should_release=${should_release}" >> $GITHUB_ENV
        echo "release_is_draft=${release_is_draft}" >> $GITHUB_ENV
        echo "release_is_prerelease=${release_is_prerelease}" >> $GITHUB_ENV
        echo "release_modifier=${release_modifier}" >> $GITHUB_ENV

    - name: Set Product Version
      run: echo "product_version=${{ env.APP_MAJOR_VERSION }}.${{ env.APP_MINOR_VERSION }}" >> $GITHUB_ENV

    - name: Set Executable Version
      run: echo "executable_version=${{ env.APP_MAJOR_VERSION }}.${{ env.APP_MINOR_VERSION }}.${{ env.build_date }}.${{ github.run_number }}${{ github.run_attempt }}${{ env.release_modifier }}" >> $GITHUB_ENV

    - name: Set Executable Build Version (for RUST)
      run: echo "executable_build_version=${{ env.APP_MAJOR_VERSION }}.${{ env.APP_MINOR_VERSION }}.${{ env.build_date }}" >> $GITHUB_ENV

    - name: Checkout
      uses: actions/checkout@v6.0.2
      with:
        fetch-depth: 0

    - name: Discover Buildable Projects
      shell: pwsh
      run: |
        Install-Module -Name PSToml -Force

        $toml_filename = "Cargo.toml"
        $contents = Get-Content $toml_filename -Raw

        $toml_object = $contents | ConvertFrom-Toml

        $projects = $toml_object.workspace.members
        Write-Host "Found $($projects.Count) Project Names"
        foreach ($project in $projects) {
          Write-Host " - $project"
        }

        $binary_names = [string]::join(',', $projects)

        echo "BINARY_NAMES=$binary_names" >> $env:GITHUB_ENV

    - name: Show Configuration
      run: env | sort

    outputs:
      build_date: ${{ env.build_date }}
      build_year: ${{ env.build_year }}
      executable_version: ${{ env.executable_version }}
      executable_build_version: ${{ env.executable_build_version }}
      product_version: ${{ env.product_version }}
      should_tag: ${{ env.should_tag }}
      should_release: ${{ env.should_release }}
      release_is_draft: ${{ env.release_is_draft }}
      release_is_prerelease: ${{ env.release_is_prerelease }}
      release_modifier: ${{ env.release_modifier }}
      binary_names: ${{ env.BINARY_NAMES }}


  ##########################################################
  ## Build for OS
  build:
    strategy:
      matrix:
        os: [ 'windows-latest' ] #, 'ubuntu-latest' ]
        arch: [ 'x64' ] #,'x86' ]
        # See : https://doc.rust-lang.org/rustc/platform-support.html
        include:
          - os: windows-latest
            arch: x64
            target: x86_64-pc-windows-msvc
            platform: windows
          - os: windows-latest
            arch: x86
            target: i686-pc-windows-msvc
            platform: windows
          - os: ubuntu-latest
            arch: x64
            target: x86_64-unknown-linux-gnu
            platform: linux
          - os: ubuntu-latest
            arch: x86
            target: i686-unknown-linux-gnu
            platform: linux

    name: Build - ${{ matrix.platform }} - ${{ matrix.arch }}

    needs: setup

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@v6.0.2

      - name: Setup Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1.15.4
        with:
          components:
            rustfmt
            clippy

      - name: Show Rust Version
        run: rustc --version

      - name: Show Rust Available Targets
        run: rustc --print target-list

      - name: Show Rust Config
        run: rustc --print cfg

      - name: Show Rust Available Toolchains
        run: rustup toolchain list

      - name: Rustfmt Check
        uses: actions-rust-lang/rustfmt@v1.1.2

      - name: Setup Rust Target
        run: rustup target add ${{ matrix.target }}

      - name: Set Cargo TOML Version Values
        shell: pwsh
        run: |
          foreach ($project in "${{ needs.setup.outputs.binary_names }}".Split(',')) {
            $project = $project.Trim()
            
            Write-Host
            Write-Host "--------------------------------------------------------------------------------"
            Write-Host "Setting version for project '$project' to '${{ needs.setup.outputs.executable_build_version }}'"

            $file_path = Join-Path $project "Cargo.toml"
            $lines = Get-Content $file_path

            $section = ""
            for ($i = 0; $i -lt $lines.Length; $i++) {
              $line = $lines[$i].Trim()

              if ($line -match '^\s*\[.*\]\s*$') {
                $section = $line.Trim('[', ']')
              }

              if ($section -eq "package" -and $line -match '^\s*version\s*=\s*".*"\s*$') {
                Write-Host "Found version line: $($i): '$line'"
                $new_line = "version = `"${{ needs.setup.outputs.executable_build_version }}`""
                $lines[$i] = $new_line
                Write-Host "  Set version line: $($i): '$new_line'"
                break
              }
            }
            
            Set-Content -Path $file_path -Value $lines

            Write-Host
            Write-Host "$file_path :"
            Get-Content $file_path
          }

      - name: Set Build Parameters
        shell: pwsh
        run: |
          $build_output_folder    = Join-Path "${{ env.BASE_BUILD_OUTPUT_FOLDER }}" "${{ matrix.platform }}" "${{ matrix.arch }}"
          $build_artifacts_folder = Join-Path "${{ env.BASE_BUILD_ARTIFACTS_FOLDER }}" "${{ matrix.platform }}" "${{ matrix.arch }}"
          
          echo "BUILD_OUTPUT_FOLDER=$build_output_folder" >> $env:GITHUB_ENV
          echo "BUILD_ARTIFACTS_FOLDER=$build_artifacts_folder" >> $env:GITHUB_ENV

      - name: Build
        run: cargo build --all-targets --future-incompat-report --profile ${{ env.BUILD_CONFIG }} --verbose --target-dir ${{ env.BUILD_OUTPUT_FOLDER }}

      #- name: Check Build Output
      #  run: sigcheck uuidgen.exe (Requires SysInternals)

      - name: Run tests
        run: cargo test --verbose --release

      - name: Debug Files - BUILD_OUTPUT_FOLDER
        shell: pwsh
        run: Get-ChildItem "${{ env.BUILD_OUTPUT_FOLDER }}" -recurse

      - name: Copy relevant files to output folder
        shell: pwsh
        run: |
          $executable_extension = ".exe"
          if ("${{ matrix.platform }}" -ne "windows") {
            $executable_extension = ""
          }

          if (-not(Test-Path "${{ env.BASE_BUILD_COLLECT_FOLDER }}" -PathType Container)) {
            New-Item -path "${{ env.BASE_BUILD_COLLECT_FOLDER }}" -ItemType Directory
          }

          Copy-Item "README.md" "${{ env.BASE_BUILD_COLLECT_FOLDER }}"

          foreach ($project in "${{ needs.setup.outputs.binary_names }}".Split(',')) {
            if ([string]::IsNullOrWhiteSpace($project)) {
              continue
            }
            
            Write-Host "Copying project to '${{ env.BASE_BUILD_COLLECT_FOLDER }}': $project"
            $project = $project.Trim()
            Copy-Item (Join-Path "${{ env.BUILD_OUTPUT_FOLDER }}" "${{ env.BUILD_CONFIG }}" "$($project)$($executable_extension)") "${{ env.BASE_BUILD_COLLECT_FOLDER }}"
          }

      - name: Debug Files - BASE_BUILD_OUTPUT_FOLDER
        shell: pwsh
        run: Get-ChildItem "${{ env.BASE_BUILD_OUTPUT_FOLDER }}" -recurse

      - name: Debug Files - BASE_BUILD_COLLECT_FOLDER
        shell: pwsh
        run: Get-ChildItem "${{ env.BASE_BUILD_COLLECT_FOLDER }}" -recurse

      - name: Compress Artifacts
        uses: OctopusDeploy/create-zip-package-action@v4.1.0
        with:
          package_id: ${{ env.PROJECT_NAME }}.${{ matrix.platform }}.${{ matrix.arch }}
          version: v${{ needs.setup.outputs.executable_version }}
          output_folder: ${{ env.BASE_BUILD_ARTIFACTS_FOLDER }}
          base_path: ${{ env.BASE_BUILD_COLLECT_FOLDER }}
          files: |
            *

      # gci |  where { $_.UnixMode -like '*x*' }

      - name: Debug Files - BUILD_ARTIFACTS_FOLDER
        shell: pwsh
        run: Get-ChildItem "${{ env.BASE_BUILD_ARTIFACTS_FOLDER }}" -recurse

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v7.0.1
        with:
          name: ${{ matrix.platform }}.${{ matrix.arch }}
          path: ${{ env.BASE_BUILD_ARTIFACTS_FOLDER }}/*.zip
          if-no-files-found: error


  ##########################################################
  ## Tag in git
  tag:
    name: Tag in GitHub
    permissions: write-all
    if: needs.setup.outputs.should_tag == 'true'

    needs:
      - setup
      - build

    runs-on: ubuntu-latest

    steps:
    - name: Tag git
      uses: pkgdeps/git-tag-action@v3.0.1
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        github_repo: ${{ github.repository }}
        git_commit_sha: ${{ github.sha }}
        git_tag_prefix: "v"
        version: ${{ needs.setup.outputs.executable_version }}


  ##########################################################
  ## Generate a GitHub Release
  release:
    name: Create GitHub Release
    permissions: write-all
    if: needs.setup.outputs.should_release == 'true'

    needs:
      - setup
      - build

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v6.0.2
      with:
        fetch-depth: 0
        fetch-tags: true

    - uses: actions/download-artifact@v8.0.1
      with:
        path: release

    - name: Debug Files - release
      shell: pwsh
      run: Get-ChildItem "release" -recurse

    - name: Build Changelog
      id: build_changelog
      uses: mikepenz/release-changelog-builder-action@v6.2.1
      with:
        failOnError: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Create Release
      uses: ncipollo/release-action@v1.21.0
      with:
        tag: v${{ needs.setup.outputs.executable_version }}
        name: Release ${{ needs.setup.outputs.executable_version }}
        body: ${{ steps.build_changelog.outputs.changelog }}
        draft: ${{ needs.setup.outputs.release_is_draft }}
        prerelease: ${{ needs.setup.outputs.release_is_prerelease }}
        removeArtifacts: true
        artifacts: 'release/**/*.zip'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
